Replace cjson with json-c-0.12
:Release Notes:
cjson replaced with json-c-0.12

:Detailed Notes:
Rename debug.h to powerd-debug.h to prevent conflict with debug.h
included in json-c. Otherwise build of audiod, sleepd, bioservice fail
with:
BUILD/sysroots/w2/usr/lib/libpowerd.so: undefined reference to `TRACE'

:Testing Performed:
Build Successful, random testing done and verified using luna commands

:QA Notes:

:Issues Addressed:
[DRD-3283] Replace cjson with json-c v0.12

Change-Id: I1a94fcc2c59caa4e973bff00608f1d271a995814
Reviewed-on: https://gpro.lgsvl.com/133754
Reviewed-by: Rohit Anand <rohit.anand@lge.com>
Tested-by: Rohit Anand <rohit.anand@lge.com>
Reviewed-by: Abhishek Srivastava <abhishek.srivastava@lge.com>